import { createClient } from '@supabase/supabase-js'

const supabaseUrl = 'https://filluppmbagrzugmcqzb.supabase.co'
const supabaseAnonKey = 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZpbGx1cHBtYmFncnp1Z21jcXpiIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDI1MzYyNDEsImV4cCI6MjA1ODExMjI0MX0.-kpwNA0qqv_Q1odhvO4DnTLGhEF4cXSXAhwJkhruuxk'
const supabaseServiceKey = 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZpbGx1cHBtYmFncnp1Z21jcXpiIiwicm9sZSI6InNlcnZpY2Vfcm9sZSIsImlhdCI6MTc0MjUzNjI0MSwiZXhwIjoyMDU4MTEyMjQxfQ.dFO4EceIXaQEWZHypz7Zk4CTBii7fWn6g8go6Jgo4Zc'

export const supabase = createClient(supabaseUrl, supabaseAnonKey)
